export const MYCOMPANY_LOAD = "MYCOMPANY_LOAD";
export const MYCOMPANY_SUCCESS = "MYCOMPANY_SUCCESS";
export const MYCOMPANY_FAIL = "MYCOMPANY_FAIL";

export const OFFER_CREATE_LOAD = "OFFER_CREATE_LOAD ";
export const OFFER_CREATE_SUCCESS = "OFFER_CREATE_SUCCESS";
export const OFFER_CREATE_FAIL = "OFFER_CREATE_FAIL";

export const MY_OFFERS_LOAD = "MY_OFFERS_LOAD ";
export const MY_OFFERS_SUCCESS = "MY_OFFERS_SUCCESS";
export const MY_OFFERS_FAIL = "MY_OFFERS_FAIL";
export const MY_OFFERS_CLEAR = "MY_OFFERS_CLEAR";

export const DELETE_OFFER_LOAD = "DELETE_OFFER_LOAD ";
export const DELETE_OFFER_SUCCESS = "DELETE_OFFER_SUCCESS";
export const DELETE_OFFER_FAIL = "DELETE_OFFER_FAIL";

export const ALL_OFFERS_LOAD = "ALL_OFFERS_LOAD ";
export const ALL_OFFERS_SUCCESS = "ALL_OFFERS_SUCCESS";
export const ALL_OFFERS_FAIL = "ALL_OFFERS_FAIL";

export const GET_OFFER_BYID_LOAD = "GET_OFFER_BYID_LOAD ";
export const GET_OFFER_BYID_SUCCESS = "GET_OFFER_BYID_SUCCESS";
export const GET_OFFER_BYID_FAIL = "GET_OFFER_BYID_FAIL";

export const COMPANY_PROFILE_CREATE_LOAD = "COMPANY_PROFILE_CREATE_LOAD ";
export const COMPANY_PROFILE_CREATE_SUCCESS = "COMPANY_PROFILE_CREATE_SUCCESS";
export const COMPANY_PROFILE_CREATE_FAIL = "COMPANY_PROFILE_CREATE_FAIL";

export const OFFRE_APPLY_LOAD = "OFFRE_APPLY_LOAD";
export const OFFRE_APPLY_SUCCESS = "OFFRE_APPLY_SUCCESS";
export const OFFRE_APPLY_FAIL = "OFFRE_APPLY_FAIL";
