export const PROFILE_LOAD = "PROFILE_LOAD";
export const PROFILE_SUCCESS = "PROFILE_SUCCESS";
export const PROFILE_FAIL = "PROFILE_FAIL";
export const PROFILE_CLEAR = "PROFILE_CLEAR";

export const PROFILE_CREATE_LOAD = "PROFILE_CREATE_LOAD ";
export const PROFILE_CREATE_SUCCESS = "PROFILE_CREATE_SUCCESS";
export const PROFILE_CREATE_FAIL = "PROFILE_CREATE_FAIL";

export const PROFILE_DELETE_LOAD = "PROFILE_DELETE_LOAD ";
export const PROFILE_DELETE_SUCCESS = "PROFILE_DELETE_SUCCESS";
export const PROFILE_DELETE_FAIL = "PROFILE_DELETE_FAIL";

export const PROFILE_ADD_EXPERIENCE_LOAD = "PROFILE_ADD_EXPERIENCE_LOAD";
export const PROFILE_ADD_EXPERIENCE_SUCCESS = "PROFILE_ADD_EXPERIENCE_SUCCESS";
export const PROFILE_ADD_EXPERIENCE_FAIL = "PROFILE_ADD_EXPERIENCE_FAIL";

export const PROFILE_ADD_EDUCATION_LOAD = "PROFILE_ADD_EDUCATION_LOAD";
export const PROFILE_ADD_EDUCATION_SUCCESS = "PROFILE_ADD_EDUCATION_SUCCESS";
export const PROFILE_ADD_EDUCATION_FAIL = "PROFILE_ADD_EDUCATION_FAIL";

export const PROFILE_DELETE_EXPERIENCE_LOAD = "PROFILE_DELETE_EXPERIENCE_LOAD";
export const PROFILE_DELETE_EXPERIENCE_SUCCESS = "PROFILE_DELETE_EXPERIENCE_SUCCESS";
export const PROFILE_DELETE_EXPERIENCE_FAIL = "PROFILE_DELETE_EXPERIENCE_FAIL";

export const PROFILE_DELETE_EDUCATION_LOAD = "PROFILE_DELETE_EDUCATION_LOAD";
export const PROFILE_DELETE_EDUCATION_SUCCESS = "PROFILE_DELETE_EDUCATION_SUCCESS";
export const PROFILE_DELETE_EDUCATION_FAIL = "PROFILE_DELETE_EDUCATION_FAIL";

export const GET_PROFILES_LOAD = "GET_PROFILES_LOAD";
export const GET_PROFILES_SUCCESS = "GET_PROFILES_SUCCESS";
export const GET_PROFILES_FAIL = "GET_PROFILES_FAIL";

export const GET_REPOS_LOAD = "GET_REPOS_LOAD";
export const GET_REPOS_SUCCESS = "GET_REPOS_SUCCESS";
export const GET_REPOS_FAIL = "GET_REPOS_FAIL";
